# Test name JWT
@testjwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU4OTY3Mzd9.kxnOLbkUQbEP2act7HNUeCk8XzmrGPHrq3CJNJoYAUY

# Benny Smith JWT
@bennyjwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzcyMDE5MDN9.DInzodSH1SlB_rvJ0kClilvHNdLKs6re0TZofOHjgR4

### PRODUCT - index all products
GET http://localhost:3000/products
# Authorization: Bearer {{jwt}}

### PRODUCT - show one product
GET http://localhost:3000/products/2

### PRODUCT - create new product
POST http://localhost:3000/products
Authorization: Bearer {{bennyjwt}}
content-type: application/json

{
  "name": "Decaf Coffee",
  "price": 50,
  "description": "doesn't contain caffeine",
  "supplier_id": 1
}

### PRODUCT - update one product
PATCH http://localhost:3000/products/15
Authorization: Bearer {{bennyjwt}}
content-type: application/json

{
  "price": 51
}

### PRODUCT - delete one product
DELETE http://localhost:3000/products/15
Authorization: Bearer {{bennyjwt}}

### SUPPLIER - index all suppliers
GET http://localhost:3000/suppliers

### USER - create new user/sign-up
POST http://localhost:3000/users
content-type: application/json

{
  "name": "Benny Smith",
  "email": "benny@smith.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSIONS - create new session/login for exisiting user
POST http://localhost:3000/sessions
content-type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### ORDER - Create new order from carted products (user must be logged in & have carted products)
POST http://localhost:3000/orders
Authorization: Bearer {{bennyjwt}}

### ORDER - index all orders (user must be logged in)
GET http://localhost:3000/orders
Authorization: Bearer {{jwt}}

### ORDER - show specific order (user must be logged in)
GET http://localhost:3000/orders/1
Authorization: Bearer {{jwt}}

### CARTED_PRODUCT - add item(s) to cart
POST http://localhost:3000/carted-products
Authorization: Bearer {{bennyjwt}}
Content-Type: application/json

{
  "product_id": 7,
  "quantity": 10
}
### CARTED_PRODUCT - index all carted products
GET http://localhost:3000/carted-products
Authorization: Bearer {{testjwt}}
###


